//------------------------------------------------------------------------------
//  ver. 1.11
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class E_Invoice {
    
    private Header headerField;
    
    private Invoice[] invoiceField;
    
    private Footer footerField;
    
    /// <remarks/>
    public Header Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Invoice")]
    public Invoice[] Invoice {
        get {
            return this.invoiceField;
        }
        set {
            this.invoiceField = value;
        }
    }
    
    /// <remarks/>
    public Footer Footer {
        get {
            return this.footerField;
        }
        set {
            this.footerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Header {
    
    private string testField;
    
    private System.DateTime dateField;
    
    private string fileIdField;
    
    private string appIdField;
    
    private string versionField;
    
    private string senderIdField;
    
    private string receiverIdField;
    
    private string contractIdField;
    
    private string payeeAccountNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
    public string Test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public string FileId {
        get {
            return this.fileIdField;
        }
        set {
            this.fileIdField = value;
        }
    }
    
    /// <remarks/>
    public string AppId {
        get {
            return this.appIdField;
        }
        set {
            this.appIdField = value;
        }
    }
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public string SenderId {
        get {
            return this.senderIdField;
        }
        set {
            this.senderIdField = value;
        }
    }
    
    /// <remarks/>
    public string ReceiverId {
        get {
            return this.receiverIdField;
        }
        set {
            this.receiverIdField = value;
        }
    }
    
    /// <remarks/>
    public string ContractId {
        get {
            return this.contractIdField;
        }
        set {
            this.contractIdField = value;
        }
    }
    
    /// <remarks/>
    public string PayeeAccountNumber {
        get {
            return this.payeeAccountNumberField;
        }
        set {
            this.payeeAccountNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AccountingRecord {
    
    private string descriptionField;
    
    private AccountingRecordJournalEntry[] journalEntryField;
    
    private string partnerCodeField;
    
    private string businessCodeField;
    
    private string sourceCodeField;
    
    private string cashFlowCodeField;
    
    private string classificatorCodeField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("JournalEntry")]
    public AccountingRecordJournalEntry[] JournalEntry {
        get {
            return this.journalEntryField;
        }
        set {
            this.journalEntryField = value;
        }
    }
    
    /// <remarks/>
    public string PartnerCode {
        get {
            return this.partnerCodeField;
        }
        set {
            this.partnerCodeField = value;
        }
    }
    
    /// <remarks/>
    public string BusinessCode {
        get {
            return this.businessCodeField;
        }
        set {
            this.businessCodeField = value;
        }
    }
    
    /// <remarks/>
    public string SourceCode {
        get {
            return this.sourceCodeField;
        }
        set {
            this.sourceCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CashFlowCode {
        get {
            return this.cashFlowCodeField;
        }
        set {
            this.cashFlowCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ClassificatorCode {
        get {
            return this.classificatorCodeField;
        }
        set {
            this.classificatorCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AccountingRecordJournalEntry {
    
    private string generalLedgerField;
    
    private string generalLedgerDetailField;
    
    private string costObjectiveField;
    
    private decimal sumField;
    
    private bool sumFieldSpecified;
    
    private decimal vatSumField;
    
    private bool vatSumFieldSpecified;
    
    private decimal vatRateField;
    
    private bool vatRateFieldSpecified;
    
    /// <remarks/>
    public string GeneralLedger {
        get {
            return this.generalLedgerField;
        }
        set {
            this.generalLedgerField = value;
        }
    }
    
    /// <remarks/>
    public string GeneralLedgerDetail {
        get {
            return this.generalLedgerDetailField;
        }
        set {
            this.generalLedgerDetailField = value;
        }
    }
    
    /// <remarks/>
    public string CostObjective {
        get {
            return this.costObjectiveField;
        }
        set {
            this.costObjectiveField = value;
        }
    }
    
    /// <remarks/>
    public decimal Sum {
        get {
            return this.sumField;
        }
        set {
            this.sumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SumSpecified {
        get {
            return this.sumFieldSpecified;
        }
        set {
            this.sumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal VatSum {
        get {
            return this.vatSumField;
        }
        set {
            this.vatSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VatSumSpecified {
        get {
            return this.vatSumFieldSpecified;
        }
        set {
            this.vatSumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal VatRate {
        get {
            return this.vatRateField;
        }
        set {
            this.vatRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VatRateSpecified {
        get {
            return this.vatRateFieldSpecified;
        }
        set {
            this.vatRateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VATRecord {
    
    private decimal sumBeforeVATField;
    
    private bool sumBeforeVATFieldSpecified;
    
    private decimal vATRateField;
    
    private bool vATRateFieldSpecified;
    
    private decimal vATSumField;
    
    private bool vATSumFieldSpecified;
    
    private string currencyField;
    
    private decimal sumAfterVATField;
    
    private bool sumAfterVATFieldSpecified;
    
    private ExtensionRecord referenceField;
    
    private string vatIdField;
    
    /// <remarks/>
    public decimal SumBeforeVAT {
        get {
            return this.sumBeforeVATField;
        }
        set {
            this.sumBeforeVATField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SumBeforeVATSpecified {
        get {
            return this.sumBeforeVATFieldSpecified;
        }
        set {
            this.sumBeforeVATFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal VATRate {
        get {
            return this.vATRateField;
        }
        set {
            this.vATRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VATRateSpecified {
        get {
            return this.vATRateFieldSpecified;
        }
        set {
            this.vATRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal VATSum {
        get {
            return this.vATSumField;
        }
        set {
            this.vATSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VATSumSpecified {
        get {
            return this.vATSumFieldSpecified;
        }
        set {
            this.vATSumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public decimal SumAfterVAT {
        get {
            return this.sumAfterVATField;
        }
        set {
            this.sumAfterVATField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SumAfterVATSpecified {
        get {
            return this.sumAfterVATFieldSpecified;
        }
        set {
            this.sumAfterVATFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ExtensionRecord Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string vatId {
        get {
            return this.vatIdField;
        }
        set {
            this.vatIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("AdditionalInformation", Namespace="", IsNullable=false)]
public partial class ExtensionRecord {
    
    private string informationNameField;
    
    private string informationContentField;
    
    private System.Xml.XmlElement customContentField;
    
    private string extensionIdField;
    
    /// <remarks/>
    public string InformationName {
        get {
            return this.informationNameField;
        }
        set {
            this.informationNameField = value;
        }
    }
    
    /// <remarks/>
    public string InformationContent {
        get {
            return this.informationContentField;
        }
        set {
            this.informationContentField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement CustomContent {
        get {
            return this.customContentField;
        }
        set {
            this.customContentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string extensionId {
        get {
            return this.extensionIdField;
        }
        set {
            this.extensionIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AdditionRecord {
    
    private string addContentField;
    
    private decimal addRateField;
    
    private bool addRateFieldSpecified;
    
    private decimal addSumField;
    
    private bool addSumFieldSpecified;
    
    private string addCodeField;
    
    /// <remarks/>
    public string AddContent {
        get {
            return this.addContentField;
        }
        set {
            this.addContentField = value;
        }
    }
    
    /// <remarks/>
    public decimal AddRate {
        get {
            return this.addRateField;
        }
        set {
            this.addRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AddRateSpecified {
        get {
            return this.addRateFieldSpecified;
        }
        set {
            this.addRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal AddSum {
        get {
            return this.addSumField;
        }
        set {
            this.addSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AddSumSpecified {
        get {
            return this.addSumFieldSpecified;
        }
        set {
            this.addSumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string addCode {
        get {
            return this.addCodeField;
        }
        set {
            this.addCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AccountDataRecord {
    
    private string accountNumberField;
    
    private string iBANField;
    
    private string bICField;
    
    private string bankNameField;
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public string IBAN {
        get {
            return this.iBANField;
        }
        set {
            this.iBANField = value;
        }
    }
    
    /// <remarks/>
    public string BIC {
        get {
            return this.bICField;
        }
        set {
            this.bICField = value;
        }
    }
    
    /// <remarks/>
    public string BankName {
        get {
            return this.bankNameField;
        }
        set {
            this.bankNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddressRecord {
    
    private string postalAddress1Field;
    
    private string postalAddress2Field;
    
    private string cityField;
    
    private string postalCodeField;
    
    private string countryField;
    
    private ExtensionRecord[] extensionField;
    
    /// <remarks/>
    public string PostalAddress1 {
        get {
            return this.postalAddress1Field;
        }
        set {
            this.postalAddress1Field = value;
        }
    }
    
    /// <remarks/>
    public string PostalAddress2 {
        get {
            return this.postalAddress2Field;
        }
        set {
            this.postalAddress2Field = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Extension")]
    public ExtensionRecord[] Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ContactDataRecord {
    
    private string contactNameField;
    
    private string contactPersonCodeField;
    
    private string phoneNumberField;
    
    private string faxNumberField;
    
    private string uRLField;
    
    private string emailAddressField;
    
    private AddressRecord legalAddressField;
    
    private AddressRecord mailAddressField;
    
    private ExtensionRecord[] contactInformationField;
    
    /// <remarks/>
    public string ContactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    public string ContactPersonCode {
        get {
            return this.contactPersonCodeField;
        }
        set {
            this.contactPersonCodeField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string FaxNumber {
        get {
            return this.faxNumberField;
        }
        set {
            this.faxNumberField = value;
        }
    }
    
    /// <remarks/>
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("E-mailAddress")]
    public string EmailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
    
    /// <remarks/>
    public AddressRecord LegalAddress {
        get {
            return this.legalAddressField;
        }
        set {
            this.legalAddressField = value;
        }
    }
    
    /// <remarks/>
    public AddressRecord MailAddress {
        get {
            return this.mailAddressField;
        }
        set {
            this.mailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContactInformation")]
    public ExtensionRecord[] ContactInformation {
        get {
            return this.contactInformationField;
        }
        set {
            this.contactInformationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BillPartyRecord {
    
    private string uniqueCodeField;
    
    private string nameField;
    
    private string depIdField;
    
    private string regNumberField;
    
    private string vATRegNumberField;
    
    private ContactDataRecord contactDataField;
    
    private AccountDataRecord[] accountInfoField;
    
    private ExtensionRecord[] extensionField;
    
    /// <remarks/>
    public string UniqueCode {
        get {
            return this.uniqueCodeField;
        }
        set {
            this.uniqueCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string DepId {
        get {
            return this.depIdField;
        }
        set {
            this.depIdField = value;
        }
    }
    
    /// <remarks/>
    public string RegNumber {
        get {
            return this.regNumberField;
        }
        set {
            this.regNumberField = value;
        }
    }
    
    /// <remarks/>
    public string VATRegNumber {
        get {
            return this.vATRegNumberField;
        }
        set {
            this.vATRegNumberField = value;
        }
    }
    
    /// <remarks/>
    public ContactDataRecord ContactData {
        get {
            return this.contactDataField;
        }
        set {
            this.contactDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AccountInfo")]
    public AccountDataRecord[] AccountInfo {
        get {
            return this.accountInfoField;
        }
        set {
            this.accountInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Extension")]
    public ExtensionRecord[] Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Invoice {
    
    private InvoiceParties invoicePartiesField;
    
    private InvoiceInformation invoiceInformationField;
    
    private InvoiceSumGroup[] invoiceSumGroupField;
    
    private InvoiceItem invoiceItemField;
    
    private ExtensionRecord[] additionalInformationField;
    
    private PaymentInfo paymentInfoField;
    
    private string invoiceIdField;
    
    private string serviceIdField;
    
    private string regNumberField;
    
    private string channelIdField;
    
    private string channelAddressField;
    
    private string factoringField;
    
    private string templateIdField;
    
    private string languageIdField;
    
    private string presentmentField;
    
    private string invoiceGlobUniqIdField;
    
    private string sellerContractIdField;
    
    private string sellerRegnumberField;
    
    /// <remarks/>
    public InvoiceParties InvoiceParties {
        get {
            return this.invoicePartiesField;
        }
        set {
            this.invoicePartiesField = value;
        }
    }
    
    /// <remarks/>
    public InvoiceInformation InvoiceInformation {
        get {
            return this.invoiceInformationField;
        }
        set {
            this.invoiceInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InvoiceSumGroup")]
    public InvoiceSumGroup[] InvoiceSumGroup {
        get {
            return this.invoiceSumGroupField;
        }
        set {
            this.invoiceSumGroupField = value;
        }
    }
    
    /// <remarks/>
    public InvoiceItem InvoiceItem {
        get {
            return this.invoiceItemField;
        }
        set {
            this.invoiceItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdditionalInformation")]
    public ExtensionRecord[] AdditionalInformation {
        get {
            return this.additionalInformationField;
        }
        set {
            this.additionalInformationField = value;
        }
    }
    
    /// <remarks/>
    public PaymentInfo PaymentInfo {
        get {
            return this.paymentInfoField;
        }
        set {
            this.paymentInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceId {
        get {
            return this.invoiceIdField;
        }
        set {
            this.invoiceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string serviceId {
        get {
            return this.serviceIdField;
        }
        set {
            this.serviceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string regNumber {
        get {
            return this.regNumberField;
        }
        set {
            this.regNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string channelId {
        get {
            return this.channelIdField;
        }
        set {
            this.channelIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string channelAddress {
        get {
            return this.channelAddressField;
        }
        set {
            this.channelAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string factoring {
        get {
            return this.factoringField;
        }
        set {
            this.factoringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string templateId {
        get {
            return this.templateIdField;
        }
        set {
            this.templateIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string languageId {
        get {
            return this.languageIdField;
        }
        set {
            this.languageIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string presentment {
        get {
            return this.presentmentField;
        }
        set {
            this.presentmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceGlobUniqId {
        get {
            return this.invoiceGlobUniqIdField;
        }
        set {
            this.invoiceGlobUniqIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sellerContractId {
        get {
            return this.sellerContractIdField;
        }
        set {
            this.sellerContractIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sellerRegnumber {
        get {
            return this.sellerRegnumberField;
        }
        set {
            this.sellerRegnumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InvoiceParties {
    
    private BillPartyRecord sellerPartyField;
    
    private BillPartyRecord buyerPartyField;
    
    private BillPartyRecord recipientPartyField;
    
    private BillPartyRecord deliveryPartyField;
    
    private BillPartyRecord payerPartyField;
    
    /// <remarks/>
    public BillPartyRecord SellerParty {
        get {
            return this.sellerPartyField;
        }
        set {
            this.sellerPartyField = value;
        }
    }
    
    /// <remarks/>
    public BillPartyRecord BuyerParty {
        get {
            return this.buyerPartyField;
        }
        set {
            this.buyerPartyField = value;
        }
    }
    
    /// <remarks/>
    public BillPartyRecord RecipientParty {
        get {
            return this.recipientPartyField;
        }
        set {
            this.recipientPartyField = value;
        }
    }
    
    /// <remarks/>
    public BillPartyRecord DeliveryParty {
        get {
            return this.deliveryPartyField;
        }
        set {
            this.deliveryPartyField = value;
        }
    }
    
    /// <remarks/>
    public BillPartyRecord PayerParty {
        get {
            return this.payerPartyField;
        }
        set {
            this.payerPartyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InvoiceInformation {
    
    private InvoiceInformationType typeField;
    
    private string factorContractNumberField;
    
    private string contractNumberField;
    
    private string documentNameField;
    
    private string invoiceNumberField;
    
    private string invoiceContentCodeField;
    
    private string invoiceContentTextField;
    
    private string paymentReferenceNumberField;
    
    private string paymentMethodField;
    
    private System.DateTime invoiceDateField;
    
    private System.DateTime dueDateField;
    
    private bool dueDateFieldSpecified;
    
    private string paymentTermField;
    
    private decimal fineRatePerDayField;
    
    private bool fineRatePerDayFieldSpecified;
    
    private InvoiceInformationPeriod periodField;
    
    private ContactDataRecord invoiceDelivererField;
    
    private ExtensionRecord[] extensionField;
    
    /// <remarks/>
    public InvoiceInformationType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string FactorContractNumber {
        get {
            return this.factorContractNumberField;
        }
        set {
            this.factorContractNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ContractNumber {
        get {
            return this.contractNumberField;
        }
        set {
            this.contractNumberField = value;
        }
    }
    
    /// <remarks/>
    public string DocumentName {
        get {
            return this.documentNameField;
        }
        set {
            this.documentNameField = value;
        }
    }
    
    /// <remarks/>
    public string InvoiceNumber {
        get {
            return this.invoiceNumberField;
        }
        set {
            this.invoiceNumberField = value;
        }
    }
    
    /// <remarks/>
    public string InvoiceContentCode {
        get {
            return this.invoiceContentCodeField;
        }
        set {
            this.invoiceContentCodeField = value;
        }
    }
    
    /// <remarks/>
    public string InvoiceContentText {
        get {
            return this.invoiceContentTextField;
        }
        set {
            this.invoiceContentTextField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentReferenceNumber {
        get {
            return this.paymentReferenceNumberField;
        }
        set {
            this.paymentReferenceNumberField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentMethod {
        get {
            return this.paymentMethodField;
        }
        set {
            this.paymentMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime InvoiceDate {
        get {
            return this.invoiceDateField;
        }
        set {
            this.invoiceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DueDate {
        get {
            return this.dueDateField;
        }
        set {
            this.dueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DueDateSpecified {
        get {
            return this.dueDateFieldSpecified;
        }
        set {
            this.dueDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string PaymentTerm {
        get {
            return this.paymentTermField;
        }
        set {
            this.paymentTermField = value;
        }
    }
    
    /// <remarks/>
    public decimal FineRatePerDay {
        get {
            return this.fineRatePerDayField;
        }
        set {
            this.fineRatePerDayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FineRatePerDaySpecified {
        get {
            return this.fineRatePerDayFieldSpecified;
        }
        set {
            this.fineRatePerDayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public InvoiceInformationPeriod Period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    public ContactDataRecord InvoiceDeliverer {
        get {
            return this.invoiceDelivererField;
        }
        set {
            this.invoiceDelivererField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Extension")]
    public ExtensionRecord[] Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InvoiceInformationType {
    
    private string sourceInvoiceField;
    
    private string typeField;
    
    /// <remarks/>
    public string SourceInvoice {
        get {
            return this.sourceInvoiceField;
        }
        set {
            this.sourceInvoiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InvoiceInformationPeriod {
    
    private string periodNameField;
    
    private System.DateTime startDateField;
    
    private bool startDateFieldSpecified;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    /// <remarks/>
    public string PeriodName {
        get {
            return this.periodNameField;
        }
        set {
            this.periodNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartDateSpecified {
        get {
            return this.startDateFieldSpecified;
        }
        set {
            this.startDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InvoiceSumGroup {
    
    private InvoiceSumGroupBalance balanceField;
    
    private decimal invoiceSumField;
    
    private bool invoiceSumFieldSpecified;
    
    private decimal penaltySumField;
    
    private bool penaltySumFieldSpecified;
    
    private AdditionRecord[] additionField;
    
    private decimal roundingField;
    
    private bool roundingFieldSpecified;
    
    private VATRecord[] vATField;
    
    private decimal totalVATSumField;
    
    private bool totalVATSumFieldSpecified;
    
    private decimal totalSumField;
    
    private decimal totalToPayField;
    
    private bool totalToPayFieldSpecified;
    
    private string currencyField;
    
    private AccountingRecord accountingField;
    
    private ExtensionRecord[] extensionField;
    
    /// <remarks/>
    public InvoiceSumGroupBalance Balance {
        get {
            return this.balanceField;
        }
        set {
            this.balanceField = value;
        }
    }
    
    /// <remarks/>
    public decimal InvoiceSum {
        get {
            return this.invoiceSumField;
        }
        set {
            this.invoiceSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvoiceSumSpecified {
        get {
            return this.invoiceSumFieldSpecified;
        }
        set {
            this.invoiceSumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal PenaltySum {
        get {
            return this.penaltySumField;
        }
        set {
            this.penaltySumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PenaltySumSpecified {
        get {
            return this.penaltySumFieldSpecified;
        }
        set {
            this.penaltySumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Addition")]
    public AdditionRecord[] Addition {
        get {
            return this.additionField;
        }
        set {
            this.additionField = value;
        }
    }
    
    /// <remarks/>
    public decimal Rounding {
        get {
            return this.roundingField;
        }
        set {
            this.roundingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RoundingSpecified {
        get {
            return this.roundingFieldSpecified;
        }
        set {
            this.roundingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VAT")]
    public VATRecord[] VAT {
        get {
            return this.vATField;
        }
        set {
            this.vATField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalVATSum {
        get {
            return this.totalVATSumField;
        }
        set {
            this.totalVATSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalVATSumSpecified {
        get {
            return this.totalVATSumFieldSpecified;
        }
        set {
            this.totalVATSumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalSum {
        get {
            return this.totalSumField;
        }
        set {
            this.totalSumField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalToPay {
        get {
            return this.totalToPayField;
        }
        set {
            this.totalToPayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalToPaySpecified {
        get {
            return this.totalToPayFieldSpecified;
        }
        set {
            this.totalToPayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public AccountingRecord Accounting {
        get {
            return this.accountingField;
        }
        set {
            this.accountingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Extension")]
    public ExtensionRecord[] Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InvoiceSumGroupBalance {
    
    private System.DateTime balanceDateField;
    
    private bool balanceDateFieldSpecified;
    
    private decimal balanceBeginField;
    
    private bool balanceBeginFieldSpecified;
    
    private decimal[] inboundField;
    
    private decimal[] outboundField;
    
    private decimal balanceEndField;
    
    private bool balanceEndFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BalanceDate {
        get {
            return this.balanceDateField;
        }
        set {
            this.balanceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BalanceDateSpecified {
        get {
            return this.balanceDateFieldSpecified;
        }
        set {
            this.balanceDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal BalanceBegin {
        get {
            return this.balanceBeginField;
        }
        set {
            this.balanceBeginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BalanceBeginSpecified {
        get {
            return this.balanceBeginFieldSpecified;
        }
        set {
            this.balanceBeginFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Inbound")]
    public decimal[] Inbound {
        get {
            return this.inboundField;
        }
        set {
            this.inboundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Outbound")]
    public decimal[] Outbound {
        get {
            return this.outboundField;
        }
        set {
            this.outboundField = value;
        }
    }
    
    /// <remarks/>
    public decimal BalanceEnd {
        get {
            return this.balanceEndField;
        }
        set {
            this.balanceEndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BalanceEndSpecified {
        get {
            return this.balanceEndFieldSpecified;
        }
        set {
            this.balanceEndFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InvoiceItem {
    
    private InvoiceTotalGroup invoiceTotalGroupField;
    
    private InvoiceItemGroup[] invoiceItemGroupField;
    
    private InvoiceItemTotalGroup invoiceItemTotalGroupField;
    
    /// <remarks/>
    public InvoiceTotalGroup InvoiceTotalGroup {
        get {
            return this.invoiceTotalGroupField;
        }
        set {
            this.invoiceTotalGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InvoiceItemGroup")]
    public InvoiceItemGroup[] InvoiceItemGroup {
        get {
            return this.invoiceItemGroupField;
        }
        set {
            this.invoiceItemGroupField = value;
        }
    }
    
    /// <remarks/>
    public InvoiceItemTotalGroup InvoiceItemTotalGroup {
        get {
            return this.invoiceItemTotalGroupField;
        }
        set {
            this.invoiceItemTotalGroupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InvoiceTotalGroup {
    
    private ItemEntry[] itemEntryField;
    
    private GroupEntry groupEntryField;
    
    private string groupIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemEntry")]
    public ItemEntry[] ItemEntry {
        get {
            return this.itemEntryField;
        }
        set {
            this.itemEntryField = value;
        }
    }
    
    /// <remarks/>
    public GroupEntry GroupEntry {
        get {
            return this.groupEntryField;
        }
        set {
            this.groupEntryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string groupId {
        get {
            return this.groupIdField;
        }
        set {
            this.groupIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ItemEntry {
    
    private string rowNoField;
    
    private string serialNumberField;
    
    private string sellerProductIdField;
    
    private string buyerProductIdField;
    
    private string taricCodeField;
    
    private AccountingRecord accountingField;
    
    private string customerRefField;
    
    private string descriptionField;
    
    private string eANField;
    
    private string initialReadingField;
    
    private string finalReadingField;
    
    private ExtensionRecord[] itemReserveField;
    
    private ItemEntryItemDetailInfo[] itemDetailInfoField;
    
    private decimal itemSumField;
    
    private bool itemSumFieldSpecified;
    
    private AdditionRecord[] additionField;
    
    private VATRecord vATField;
    
    private decimal itemTotalField;
    
    private bool itemTotalFieldSpecified;
    
    /// <remarks/>
    public string RowNo {
        get {
            return this.rowNoField;
        }
        set {
            this.rowNoField = value;
        }
    }
    
    /// <remarks/>
    public string SerialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    public string SellerProductId {
        get {
            return this.sellerProductIdField;
        }
        set {
            this.sellerProductIdField = value;
        }
    }
    
    /// <remarks/>
    public string BuyerProductId {
        get {
            return this.buyerProductIdField;
        }
        set {
            this.buyerProductIdField = value;
        }
    }
    
    /// <remarks/>
    public string TaricCode {
        get {
            return this.taricCodeField;
        }
        set {
            this.taricCodeField = value;
        }
    }
    
    /// <remarks/>
    public AccountingRecord Accounting {
        get {
            return this.accountingField;
        }
        set {
            this.accountingField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerRef {
        get {
            return this.customerRefField;
        }
        set {
            this.customerRefField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string EAN {
        get {
            return this.eANField;
        }
        set {
            this.eANField = value;
        }
    }
    
    /// <remarks/>
    public string InitialReading {
        get {
            return this.initialReadingField;
        }
        set {
            this.initialReadingField = value;
        }
    }
    
    /// <remarks/>
    public string FinalReading {
        get {
            return this.finalReadingField;
        }
        set {
            this.finalReadingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemReserve")]
    public ExtensionRecord[] ItemReserve {
        get {
            return this.itemReserveField;
        }
        set {
            this.itemReserveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemDetailInfo")]
    public ItemEntryItemDetailInfo[] ItemDetailInfo {
        get {
            return this.itemDetailInfoField;
        }
        set {
            this.itemDetailInfoField = value;
        }
    }
    
    /// <remarks/>
    public decimal ItemSum {
        get {
            return this.itemSumField;
        }
        set {
            this.itemSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ItemSumSpecified {
        get {
            return this.itemSumFieldSpecified;
        }
        set {
            this.itemSumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Addition")]
    public AdditionRecord[] Addition {
        get {
            return this.additionField;
        }
        set {
            this.additionField = value;
        }
    }
    
    /// <remarks/>
    public VATRecord VAT {
        get {
            return this.vATField;
        }
        set {
            this.vATField = value;
        }
    }
    
    /// <remarks/>
    public decimal ItemTotal {
        get {
            return this.itemTotalField;
        }
        set {
            this.itemTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ItemTotalSpecified {
        get {
            return this.itemTotalFieldSpecified;
        }
        set {
            this.itemTotalFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ItemEntryItemDetailInfo {
    
    private string itemUnitField;
    
    private decimal itemAmountField;
    
    private bool itemAmountFieldSpecified;
    
    private decimal itemPriceField;
    
    private bool itemPriceFieldSpecified;
    
    /// <remarks/>
    public string ItemUnit {
        get {
            return this.itemUnitField;
        }
        set {
            this.itemUnitField = value;
        }
    }
    
    /// <remarks/>
    public decimal ItemAmount {
        get {
            return this.itemAmountField;
        }
        set {
            this.itemAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ItemAmountSpecified {
        get {
            return this.itemAmountFieldSpecified;
        }
        set {
            this.itemAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal ItemPrice {
        get {
            return this.itemPriceField;
        }
        set {
            this.itemPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ItemPriceSpecified {
        get {
            return this.itemPriceFieldSpecified;
        }
        set {
            this.itemPriceFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GroupEntry {
    
    private string groupDescriptionField;
    
    private ExtensionRecord[] extensionField;
    
    private AccountingRecord accountingField;
    
    private decimal groupAmountField;
    
    private bool groupAmountFieldSpecified;
    
    private decimal groupSumField;
    
    private bool groupSumFieldSpecified;
    
    private AdditionRecord[] additionField;
    
    private VATRecord vATField;
    
    private decimal groupTotalField;
    
    private bool groupTotalFieldSpecified;
    
    /// <remarks/>
    public string GroupDescription {
        get {
            return this.groupDescriptionField;
        }
        set {
            this.groupDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Extension")]
    public ExtensionRecord[] Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    public AccountingRecord Accounting {
        get {
            return this.accountingField;
        }
        set {
            this.accountingField = value;
        }
    }
    
    /// <remarks/>
    public decimal GroupAmount {
        get {
            return this.groupAmountField;
        }
        set {
            this.groupAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GroupAmountSpecified {
        get {
            return this.groupAmountFieldSpecified;
        }
        set {
            this.groupAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal GroupSum {
        get {
            return this.groupSumField;
        }
        set {
            this.groupSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GroupSumSpecified {
        get {
            return this.groupSumFieldSpecified;
        }
        set {
            this.groupSumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Addition")]
    public AdditionRecord[] Addition {
        get {
            return this.additionField;
        }
        set {
            this.additionField = value;
        }
    }
    
    /// <remarks/>
    public VATRecord VAT {
        get {
            return this.vATField;
        }
        set {
            this.vATField = value;
        }
    }
    
    /// <remarks/>
    public decimal GroupTotal {
        get {
            return this.groupTotalField;
        }
        set {
            this.groupTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GroupTotalSpecified {
        get {
            return this.groupTotalFieldSpecified;
        }
        set {
            this.groupTotalFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InvoiceItemGroup {
    
    private ItemEntry[] itemEntryField;
    
    private GroupEntry groupEntryField;
    
    private string groupIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemEntry")]
    public ItemEntry[] ItemEntry {
        get {
            return this.itemEntryField;
        }
        set {
            this.itemEntryField = value;
        }
    }
    
    /// <remarks/>
    public GroupEntry GroupEntry {
        get {
            return this.groupEntryField;
        }
        set {
            this.groupEntryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string groupId {
        get {
            return this.groupIdField;
        }
        set {
            this.groupIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InvoiceItemTotalGroup {
    
    private string invoiceItemTotalDescriptionField;
    
    private ExtensionRecord[] extensionField;
    
    private AccountingRecord accountingField;
    
    private decimal invoiceItemTotalAmountField;
    
    private bool invoiceItemTotalAmountFieldSpecified;
    
    private decimal invoiceItemTotalSumField;
    
    private bool invoiceItemTotalSumFieldSpecified;
    
    private AdditionRecord[] additionField;
    
    private VATRecord vATField;
    
    private decimal invoiceItemTotalField;
    
    private bool invoiceItemTotalFieldSpecified;
    
    /// <remarks/>
    public string InvoiceItemTotalDescription {
        get {
            return this.invoiceItemTotalDescriptionField;
        }
        set {
            this.invoiceItemTotalDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Extension")]
    public ExtensionRecord[] Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    public AccountingRecord Accounting {
        get {
            return this.accountingField;
        }
        set {
            this.accountingField = value;
        }
    }
    
    /// <remarks/>
    public decimal InvoiceItemTotalAmount {
        get {
            return this.invoiceItemTotalAmountField;
        }
        set {
            this.invoiceItemTotalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvoiceItemTotalAmountSpecified {
        get {
            return this.invoiceItemTotalAmountFieldSpecified;
        }
        set {
            this.invoiceItemTotalAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal InvoiceItemTotalSum {
        get {
            return this.invoiceItemTotalSumField;
        }
        set {
            this.invoiceItemTotalSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvoiceItemTotalSumSpecified {
        get {
            return this.invoiceItemTotalSumFieldSpecified;
        }
        set {
            this.invoiceItemTotalSumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Addition")]
    public AdditionRecord[] Addition {
        get {
            return this.additionField;
        }
        set {
            this.additionField = value;
        }
    }
    
    /// <remarks/>
    public VATRecord VAT {
        get {
            return this.vATField;
        }
        set {
            this.vATField = value;
        }
    }
    
    /// <remarks/>
    public decimal InvoiceItemTotal {
        get {
            return this.invoiceItemTotalField;
        }
        set {
            this.invoiceItemTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvoiceItemTotalSpecified {
        get {
            return this.invoiceItemTotalFieldSpecified;
        }
        set {
            this.invoiceItemTotalFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PaymentInfo {
    
    private string currencyField;
    
    private string[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string payableField;
    
    private System.DateTime payDueDateField;
    
    private bool payDueDateFieldSpecified;
    
    private decimal paymentTotalSumField;
    
    private string payerNameField;
    
    private string paymentIdField;
    
    private string payToAccountField;
    
    private string payToNameField;
    
    private string payToBICField;
    
    private string directDebitPayeeContractNumberField;
    
    private string directDebitPayerNumberField;
    
    /// <remarks/>
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PaymentDescription", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PaymentRefId", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
    public string Payable {
        get {
            return this.payableField;
        }
        set {
            this.payableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime PayDueDate {
        get {
            return this.payDueDateField;
        }
        set {
            this.payDueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PayDueDateSpecified {
        get {
            return this.payDueDateFieldSpecified;
        }
        set {
            this.payDueDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal PaymentTotalSum {
        get {
            return this.paymentTotalSumField;
        }
        set {
            this.paymentTotalSumField = value;
        }
    }
    
    /// <remarks/>
    public string PayerName {
        get {
            return this.payerNameField;
        }
        set {
            this.payerNameField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentId {
        get {
            return this.paymentIdField;
        }
        set {
            this.paymentIdField = value;
        }
    }
    
    /// <remarks/>
    public string PayToAccount {
        get {
            return this.payToAccountField;
        }
        set {
            this.payToAccountField = value;
        }
    }
    
    /// <remarks/>
    public string PayToName {
        get {
            return this.payToNameField;
        }
        set {
            this.payToNameField = value;
        }
    }
    
    /// <remarks/>
    public string PayToBIC {
        get {
            return this.payToBICField;
        }
        set {
            this.payToBICField = value;
        }
    }
    
    /// <remarks/>
    public string DirectDebitPayeeContractNumber {
        get {
            return this.directDebitPayeeContractNumberField;
        }
        set {
            this.directDebitPayeeContractNumberField = value;
        }
    }
    
    /// <remarks/>
    public string DirectDebitPayerNumber {
        get {
            return this.directDebitPayerNumberField;
        }
        set {
            this.directDebitPayerNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    PaymentDescription,
    
    /// <remarks/>
    PaymentRefId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Footer {
    
    private string totalNumberInvoicesField;
    
    private decimal totalAmountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string TotalNumberInvoices {
        get {
            return this.totalNumberInvoicesField;
        }
        set {
            this.totalNumberInvoicesField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalAmount {
        get {
            return this.totalAmountField;
        }
        set {
            this.totalAmountField = value;
        }
    }
}
